// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20251004190809_InitialCompositeDesign")]
    partial class InitialCompositeDesign
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.AccessControl.Feature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Features", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 10, 4, 22, 8, 8, 732, DateTimeKind.Local).AddTicks(3579),
                            Description = "Create new user",
                            IsActive = true,
                            IsDeleted = false,
                            Key = "USER_CREATE",
                            Name = "CanCreateUser",
                            UpdatedDate = new DateTime(2025, 10, 4, 22, 8, 8, 732, DateTimeKind.Local).AddTicks(3581)
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 10, 4, 22, 8, 8, 732, DateTimeKind.Local).AddTicks(3585),
                            Description = "View all users",
                            IsActive = true,
                            IsDeleted = false,
                            Key = "USER_VIEW",
                            Name = "CanViewUsers",
                            UpdatedDate = new DateTime(2025, 10, 4, 22, 8, 8, 732, DateTimeKind.Local).AddTicks(3586)
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2025, 10, 4, 22, 8, 8, 732, DateTimeKind.Local).AddTicks(3589),
                            Description = "Assign role to user",
                            IsActive = true,
                            IsDeleted = false,
                            Key = "ROLE_ASSIGN",
                            Name = "CanAssignRoleToUser",
                            UpdatedDate = new DateTime(2025, 10, 4, 22, 8, 8, 732, DateTimeKind.Local).AddTicks(3590)
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2025, 10, 4, 22, 8, 8, 732, DateTimeKind.Local).AddTicks(3593),
                            Description = "Assign feature to role",
                            IsActive = true,
                            IsDeleted = false,
                            Key = "FEATURE_ASSIGN",
                            Name = "CanAssignFeatureToRole",
                            UpdatedDate = new DateTime(2025, 10, 4, 22, 8, 8, 732, DateTimeKind.Local).AddTicks(3594)
                        });
                });

            modelBuilder.Entity("Domain.Models.AccessControl.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 10, 4, 22, 8, 8, 732, DateTimeKind.Local).AddTicks(3486),
                            Description = "System Administrator",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Admin",
                            UpdatedDate = new DateTime(2025, 10, 4, 22, 8, 8, 732, DateTimeKind.Local).AddTicks(3529)
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 10, 4, 22, 8, 8, 732, DateTimeKind.Local).AddTicks(3537),
                            Description = "Hotel Staff",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Staff",
                            UpdatedDate = new DateTime(2025, 10, 4, 22, 8, 8, 732, DateTimeKind.Local).AddTicks(3538)
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2025, 10, 4, 22, 8, 8, 732, DateTimeKind.Local).AddTicks(3541),
                            Description = "Regular Customer",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Customer",
                            UpdatedDate = new DateTime(2025, 10, 4, 22, 8, 8, 732, DateTimeKind.Local).AddTicks(3542)
                        });
                });

            modelBuilder.Entity("Domain.Models.AccessControl.RoleFeature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FeatureId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FeatureId");

                    b.HasIndex("RoleId", "FeatureId")
                        .IsUnique();

                    b.ToTable("RoleFeatures", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 10, 4, 22, 8, 8, 732, DateTimeKind.Local).AddTicks(4031),
                            FeatureId = 1,
                            IsActive = true,
                            IsDeleted = false,
                            RoleId = 1,
                            UpdatedDate = new DateTime(2025, 10, 4, 22, 8, 8, 732, DateTimeKind.Local).AddTicks(4033)
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 10, 4, 22, 8, 8, 732, DateTimeKind.Local).AddTicks(4035),
                            FeatureId = 2,
                            IsActive = true,
                            IsDeleted = false,
                            RoleId = 1,
                            UpdatedDate = new DateTime(2025, 10, 4, 22, 8, 8, 732, DateTimeKind.Local).AddTicks(4036)
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2025, 10, 4, 22, 8, 8, 732, DateTimeKind.Local).AddTicks(4038),
                            FeatureId = 3,
                            IsActive = true,
                            IsDeleted = false,
                            RoleId = 1,
                            UpdatedDate = new DateTime(2025, 10, 4, 22, 8, 8, 732, DateTimeKind.Local).AddTicks(4039)
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2025, 10, 4, 22, 8, 8, 732, DateTimeKind.Local).AddTicks(4041),
                            FeatureId = 4,
                            IsActive = true,
                            IsDeleted = false,
                            RoleId = 1,
                            UpdatedDate = new DateTime(2025, 10, 4, 22, 8, 8, 732, DateTimeKind.Local).AddTicks(4042)
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2025, 10, 4, 22, 8, 8, 732, DateTimeKind.Local).AddTicks(4044),
                            FeatureId = 2,
                            IsActive = true,
                            IsDeleted = false,
                            RoleId = 2,
                            UpdatedDate = new DateTime(2025, 10, 4, 22, 8, 8, 732, DateTimeKind.Local).AddTicks(4045)
                        });
                });

            modelBuilder.Entity("Domain.Models.AccessControl.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 10, 4, 22, 8, 8, 732, DateTimeKind.Local).AddTicks(3999),
                            IsActive = true,
                            IsDeleted = false,
                            RoleId = 1,
                            UpdatedDate = new DateTime(2025, 10, 4, 22, 8, 8, 732, DateTimeKind.Local).AddTicks(4002),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 10, 4, 22, 8, 8, 732, DateTimeKind.Local).AddTicks(4006),
                            IsActive = true,
                            IsDeleted = false,
                            RoleId = 2,
                            UpdatedDate = new DateTime(2025, 10, 4, 22, 8, 8, 732, DateTimeKind.Local).AddTicks(4007),
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2025, 10, 4, 22, 8, 8, 732, DateTimeKind.Local).AddTicks(4010),
                            IsActive = true,
                            IsDeleted = false,
                            RoleId = 3,
                            UpdatedDate = new DateTime(2025, 10, 4, 22, 8, 8, 732, DateTimeKind.Local).AddTicks(4011),
                            UserId = 3
                        });
                });

            modelBuilder.Entity("Domain.Models.Reservation.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CheckIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CheckOut")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("RoomId", "CheckIn");

                    b.HasIndex("RoomId", "CheckOut");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("Domain.Models.Room.Facility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Facilities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Wi-Fi"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Air Conditioning"
                        },
                        new
                        {
                            Id = 3,
                            Name = "TV"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Private Bathroom"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Work Desk"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Private Balcony"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Jacuzzi"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Hair Dryer"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Electric Kettle"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Daily Housekeeping"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Sea View"
                        });
                });

            modelBuilder.Entity("Domain.Models.Room.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PricePerNight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("Domain.Models.Room.RoomFacility", b =>
                {
                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<int>("FacilityId")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("RoomId", "FacilityId");

                    b.HasIndex("FacilityId");

                    b.ToTable("RoomFacilities");
                });

            modelBuilder.Entity("Domain.Models.Room.RoomPicture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("RoomPictures");
                });

            modelBuilder.Entity("Domain.Models.Users.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NationalId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId1")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex("UserId1")
                        .IsUnique()
                        .HasFilter("[UserId1] IS NOT NULL");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Domain.Models.Users.Staff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId1")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex("UserId1")
                        .IsUnique()
                        .HasFilter("[UserId1] IS NOT NULL");

                    b.ToTable("Staff");
                });

            modelBuilder.Entity("Domain.Models.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "HQ Office",
                            City = "Cairo",
                            Country = "Egypt",
                            CreatedDate = new DateTime(2025, 10, 4, 22, 8, 8, 732, DateTimeKind.Local).AddTicks(3607),
                            Email = "admin@hotel.com",
                            FirstName = "System",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Admin",
                            PasswordHash = "6G94qKPK8LYNjnTllCqm2G3BUM08AzOK7yW30tfjrMc=",
                            PhoneNumber = "01000000001",
                            UpdatedDate = new DateTime(2025, 10, 4, 22, 8, 8, 732, DateTimeKind.Local).AddTicks(3609),
                            Username = "jGl25bVBBBW96Qi9Te4V37Fnqchz/Eu4qB9vKrRIqRg="
                        },
                        new
                        {
                            Id = 2,
                            Address = "Hotel Reception",
                            City = "Cairo",
                            Country = "Egypt",
                            CreatedDate = new DateTime(2025, 10, 4, 22, 8, 8, 732, DateTimeKind.Local).AddTicks(3881),
                            Email = "staff@hotel.com",
                            FirstName = "Hotel",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Staff",
                            PasswordHash = "39SPNjOKo2Io67niBLumtOGNsLYj4lxFiQHtyDH7GOk=",
                            PhoneNumber = "01000000002",
                            UpdatedDate = new DateTime(2025, 10, 4, 22, 8, 8, 732, DateTimeKind.Local).AddTicks(3884),
                            Username = "FWIgZUPadkEjwhvVJGdPCoqvSciol0TJc1L+Z39+QAY="
                        },
                        new
                        {
                            Id = 3,
                            Address = "Main Street",
                            City = "Giza",
                            Country = "Egypt",
                            CreatedDate = new DateTime(2025, 10, 4, 22, 8, 8, 732, DateTimeKind.Local).AddTicks(3913),
                            Email = "customer@hotel.com",
                            FirstName = "John",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Doe",
                            PasswordHash = "mOxlSo3yj48PjwIiBIPUaRa4UBfeC3TY7HVcKMuFOag=",
                            PhoneNumber = "01000000003",
                            UpdatedDate = new DateTime(2025, 10, 4, 22, 8, 8, 732, DateTimeKind.Local).AddTicks(3914),
                            Username = "tsRYY4deNEh8o8FV7RRe/hKnRYHie+/sWqZhuO6Mpt0="
                        });
                });

            modelBuilder.Entity("Domain.Models.AccessControl.RoleFeature", b =>
                {
                    b.HasOne("Domain.Models.AccessControl.Feature", "Feature")
                        .WithMany("RoleFeatures")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.AccessControl.Role", "Role")
                        .WithMany("RoleFeatures")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feature");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Domain.Models.AccessControl.UserRole", b =>
                {
                    b.HasOne("Domain.Models.AccessControl.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Models.Users.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Models.Reservation.Reservation", b =>
                {
                    b.HasOne("Domain.Models.Users.Customer", null)
                        .WithMany("Reservations")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Room.Room", null)
                        .WithMany("Reservations")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Models.Room.RoomFacility", b =>
                {
                    b.HasOne("Domain.Models.Room.Facility", "Facility")
                        .WithMany("RoomFacilities")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Room.Room", "Room")
                        .WithMany("RoomFacilities")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Facility");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Domain.Models.Room.RoomPicture", b =>
                {
                    b.HasOne("Domain.Models.Room.Room", "Room")
                        .WithMany("Pictures")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Domain.Models.Users.Customer", b =>
                {
                    b.HasOne("Domain.Models.Users.User", "User")
                        .WithOne()
                        .HasForeignKey("Domain.Models.Users.Customer", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Users.User", null)
                        .WithOne("Customer")
                        .HasForeignKey("Domain.Models.Users.Customer", "UserId1");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Models.Users.Staff", b =>
                {
                    b.HasOne("Domain.Models.Users.User", "User")
                        .WithOne()
                        .HasForeignKey("Domain.Models.Users.Staff", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Users.User", null)
                        .WithOne("Staff")
                        .HasForeignKey("Domain.Models.Users.Staff", "UserId1");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Models.AccessControl.Feature", b =>
                {
                    b.Navigation("RoleFeatures");
                });

            modelBuilder.Entity("Domain.Models.AccessControl.Role", b =>
                {
                    b.Navigation("RoleFeatures");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Domain.Models.Room.Facility", b =>
                {
                    b.Navigation("RoomFacilities");
                });

            modelBuilder.Entity("Domain.Models.Room.Room", b =>
                {
                    b.Navigation("Pictures");

                    b.Navigation("Reservations");

                    b.Navigation("RoomFacilities");
                });

            modelBuilder.Entity("Domain.Models.Users.Customer", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("Domain.Models.Users.User", b =>
                {
                    b.Navigation("Customer");

                    b.Navigation("Staff");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
